version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - elk

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      # - logstash-logs:/usr/share/logstash/logs
    ports:
      - 5004:5004
      - 5044:5044
    depends_on:
      - elasticsearch
      - kafka
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

  log-generator:
    build: ./log-generator
    container_name: log-generator
    depends_on:
      - kafka
    networks:
      - elk

  log-generator-2:
    build: ./log-generator-2
    container_name: log-generator-2
    depends_on:
      - kafka
    networks:
      - elk

  log-generator-3:
    build: ./log-generator-3
    container_name: log-generator-3
    depends_on:
      - kafka
    networks:
      - elk
  
networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local
  # logstash-logs:
  #   driver: local
